# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c86fcc71a8296fd5ce21564af8d9943bfce0325b793e27af4e8c3fc139ac05c64145982e43d3a288cb50d3c51780ef40b2ffacb2af95c7f66f8f98e2babb58

test:
  secret_key_base: 342945257c5efeb599ebe9a96691b789d20d11efad0620d5f73b1cf868567bd2401e904ac3723620598ab0dec8aecf53368966d84d2a19d5533d1cd4a3c1e9d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
